### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [iancleary/ivy-lee-backend#63]
Hey there!!

I have a suggestion - Under the Ivy Lee Method I would like to add a brief history about the "making of the method"
I would like to send a PR if you like my idea

Attaching Screenshot below :

![image](https://user-images.githubusercontent.com/121221252/214522360-24c36787-1772-485e-a938-9c4f510da108.png)

**Comment by iancleary** [comment]
@the-amazing-atharva I would accept this pull request, thanks 😊!

It would help introduce the method to new readers coming to the README for the first time.

**Comment by the-amazing-atharva** [comment]
Thanks for the reply!

Creating a PR now
